import 'dart:convert';

import 'package:http/http.dart' as http;

class API {
  Future<List> call_api(
      String search, String type, String model, String search_lang) async {
    var response = await http.post(
        Uri.parse(
          "http://127.0.0.1:8000/core/questions",
        ),
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods':
              'POST, GET, OPTIONS, PUT, DELETE, HEAD',
          'Access-Control-Allow-Headers':
              'custId, appId, Origin, Content-Type, Cookie, X-CSRF-TOKEN, Accept, Authorization, X-XSRF-TOKEN, Access-Control-Allow-Origin',
          'Access-Control-Max-Age': '3600'
        },
        body: {
          "question": search,
          "question_word": "Nedir",
          "password": "1941",
          "model": model,
          "type": type,
          "lang": search_lang,
          "answer": ""
        });

    var parsed = jsonDecode(response.body);
    String answer = "answer";
    if (response.statusCode == 200) {
      answer = parsed["answer"].toString();
    } else {
      answer = "ERROR";
    }
    var len;
    var answers;
    try {
      len = parsed["len"];
      answers = [answer, len];
    } catch (e) {
      print(e);
      answers = [answer];
    }
    return answers;
  }
}

List list_2022 = [
  'YouTube',
  'Türkiye',
  '2022 FIFA Dünya Kupası',
  'FIFA Dünya Kupası',
  '2023 UEFA ülkeler sıralaması',
  'Bergen (şarkıcı)',
  'Nüfuslarına göre ülkeler listesi',
  'Mustafa Kemal Atatürk',
  'Ümit Özdağ',
  'II. Elizabeth',
  'Recep Tayyip Erdoğan',
  'NATO üyesi ülkeler',
  'Instagram',
  'Osmanlı İmparatorluğu',
  'Osmanlı padişahları listesi',
  'İstanbul',
  'Cristiano Ronaldo',
  'Montrö Boğazlar Sözleşmesi',
  'Ukrayna',
  'II. Abdülhamid',
  'Jeffrey Dahmer',
  'Amerika Birleşik Devletleri',
  'Lozan Antlaşması',
  'Bir sonraki Türkiye genel seçimleri için yapılan anketler',
  'Süper Lig şampiyonları listesi',
  'UEFA Şampiyonlar Ligi',
  'Dünya',
  'I. Süleyman',
  'Seks pozisyonları',
  'II. Mehmed',
  'Türkiye cumhurbaşkanları listesi',
  'II. Dünya Savaşı',
  'Google',
  'Netflix',
  'WhatsApp',
  'I. Dünya Savaşı',
  'Elon Musk',
  'Bir sonraki Türkiye parlamento seçimleri için yapılananketler (sayfa mevcut değil)',
  'Muhammed',
  'Lionel Messi',
  'Rusya',
  'YouTube erişiminin engellenmesi',
  'E-Devlet (Türkiye)',
  'Osman Gazi',
  'Süper Lig',
  'Fenerbahçe (futbol takımı)',
  'Vladimir Putin',
  '2022 UEFA ülkeler sıralaması',
  'Yüzölçümlerine göreülkeler listesi',
  'Ekrem İmamoğlu',
  'I. Selim',
  'Carles Puigdemont',
  'Rusya-Ukrayna Savaşı',
  'Galatasaray (futbol takımı)',
  'Çirmen Muharebesi',
  'Alp Arslan',
  'Türkiye başbakanları listesi',
  'NATO',
  'Kurtlar Vadisi karakterleri listesi',
  'IV. Murad',
  'Esat Oktay Yıldıran',
  'Türk Kurtuluş Savaşı',
  '29 Ekim Cumhuriyet Bayramı',
  'Ülkeler listesi',
  'Türk Silahlı Kuvvetleri',
  'Almanya',
  'Gelsin Hayat Bildiği Gibi (dizi)',
  'II. Selim',
  'İntihar yöntemleri',
  'Cem Uzan',
  'Sovyetler Birliği',
  'Cüneyt Arkın',
  'Kurtlar Vadisi Pusu karakterleri listesi',
  'Aziz Sancar',
  'PKK',
  'Hürrem Sultan',
  'Diana (Galler prensesi)',
  'Kemal Kılıçdaroğlu',
  'Çanakkale Savaşı',
  'Anal seks',
  'Cengiz Han',
  'Birleşik Krallık',
  'Uluslararası plaka işaretleri',
  'Cumhuriyet Halk Partisi',
  'Twitter',
  'Adolf Hitler',
  'Google Çeviri',
  'I. Ahmed',
  'Abdullah Öcalan',
  'III. Mehmed',
  'VI. Mehmed',
  'UEFA Avrupa Ligi',
  'Zafer Partisi',
  'Deniz Gezmiş',
  'Azerbaycan',
  'Meral Akşener',
  'Burçlar',
  'İsmet İnönü',
  'Adalet ve Kalkınma Partisi',
  'Türk dizileri listesi',
  'Büyük Selçuklu İmparatorluğu',
  'Selçuk Bayraktar',
  'Periyodik tablo',
  'VII. Kleopatra',
  "Nüfusuna göre Türkiye'nin illeri",
  'Avrupa Birliği',
  'Kurtlar Vadisi (dizi)',
  'Facebook',
  'Roblox',
  'III. Murad',
  "Türkiye'nin en zengin 100 ailesi listesi",
  'Cinsel ilişki',
  "2022 Rusya'nın Ukrayna'yı işgali",
  'Volodimir Zelenski',
  'Türkler',
  'Gmail',
  'Türkçe',
  "Türkiye'de asgari ücret",
  'Göbeklitepe',
  "Türkiye'deki siyasi partiler listesi",
  'II. Osman',
  'Ülke bayrakları listesi',
  'Jorge Jesus',
  'Fransa',
  'Albert Einstein',
  'Adnan Menderes',
  '2022 Dünya Kadınlar Voleybol Şampiyonası',
  'Survivor 2021',
  'İran',
  'Fethullah Gülen',
  'Yunan mitolojisi',
  'Dilber Ay',
  'Türk alfabesi',
  'Porno film',
  'Fatma Girik',
  'Survivor 2022: All Star',
  'Ayasofya',
  'Kemal Sunal',
  'Nureddin Nebati',
  'Türk Hava Kuvvetleri',
  'Fas',
  'Kıbrıs Harekâtı',
  'Enver Paşa',
  'Ankara',
  '12 Eylül Darbesi',
  'I. Mustafa',
  'Mahmut Ustaosmanoğlu',
  'Oral seks',
  '30 Ağustos Zafer Bayramı',
  'Kösem Sultan',
  '69 (seks pozisyonu)',
  'Mansur Yavaş',
  'Okey 101',
  'Kazakistan',
  'Nikola Tesla',
  'Kurtlar Vadisi Pusu',
  'İsviçre',
  'Arka Sokaklar (dizi)',
  '15 Temmuz Darbe Girişimi',
  'Hakan Fidan',
  'Sahibinden.com',
  'Ahmet Burak Erdoğan',
  'İngiltere',
  'Abdullah Çatlı',
  'Çin',
  'Meslekler listesi',
  'Trendyol',
  'İbrahim Tatlıses',
  'Osman Kavala',
  'İttihat ve Terakki',
  'Abdülmecid',
  'Bülent Ecevit',
  'Pınar Deniz',
  'Orhan Gazi',
  'II. Mahmud',
  'II. Bayezid',
  'Yunanistan',
  'Timur',
  'Roma İmparatorluğu',
  'Kürtler',
  'Dede Korkut Kitabı',
  'Selahaddin Eyyubi',
  'Ahmet Kaya',
  'Bir sonraki Türkiye cumhurbaşkanlığı seçimi için yapılan anketler (sayfa mevcut değil)',
  'I. Bayezid',
  'Turgut Özal',
  'II. Murad',
  'Süleyman Demirel',
  'XNXX',
  'Türkiye futbol şampiyonları listesi',
  'Togg',
  'Kuzey Kıbrıs Türk Cumhuriyeti',
  'Türkiye Büyük Millet Meclisi',
  'Devlet Bahçeli',
  'Misyoner pozisyonu',
  'Arjantin',
  'Baykar Bayraktar TB2',
  'Anadolu Selçuklu Devleti',
  'Naim Süleymanoğlu',
  'Survivor Türkiye',
  'İbn-i Sina',
  'VI. George',
  'Sakarya Meydan Muharebesi',
  'Beşiktaş (futbol takımı)',
  'Bir sonraki Türkiye genel seçimleri',
  'Oktay Sinanoğlu',
  'Japonya',
  '6-7 Eylül Olayları',
  'Celâl Şengör',
  'İlber Ortaylı',
  'Kenan Evren',
  'İngilizce',
  'Türk bilim insanları listesi',
  "İstanbul'un Fethi",
  'Ali Koç',
  'Marvel Sinematik Evreni filmleri listesi',
  'Acun Ilıcalı',
  'Senden Daha Güzel (dizi)',
  'Çernobil Faciası',
  'Necmettin Erbakan',
  'Ülke çapında 2023 Türkiye genel seçimleri için yapılan anketler',
  'Barbaros Hayreddin Paşa',
  'Müslüm Gürses',
  'Orhun Yazıtları',
  'Mehmet Âkif Ersoy',
  'Kişi başına nominal GSYİH değerlerine göre ülkeler listesi',
  'Türk Hava Yolları',
  '27 Mayıs Darbesi',
  'Kanada',
  'Atatürk İlkeleri',
  'Türkiye millî futbol takımı',
  'Türk devletleri listesi',
  'Tansu Çiller',
  'Mahmut Yıldırım',
  '2018 Türkiye genel seçimleri',
  'Abdülaziz',
  'Ali Babacan',
  'IV. Mehmed',
  'Hollanda',
  'İsa',
  'Şehzade Mustafa',
  "Muğla'nın ilçeleri",
  'Nâzım Hikmet',
  'Afra Saraçoğlu',
  'Yılmaz Güney',
  'Halkların Demokratik Partisi',
  "İslam'ın beş şartı",
  'Kylian Mbappé',
  'Mimar Sinan',
  '1915 Çanakkale Köprüsü',
  'Sabahattin Ali',
  'III. Selim',
  'Sedat Peker',
  'Katar',
  'V. Mehmed',
  'Baba (dizi, 2022)',
  'Göktürk Kağanlığı',
  'Marilyn Monroe',
  'III. Charles',
  'İtalya',
  'Kız Kulesi',
  'Süleyman Soylu',
  'Yunus Emre',
  'Necip Fazıl Kısakürek',
  'Vehbi Koç',
  'Nominal GSYİH değerlerine göre ülkeler listesi',
  'Faroe Adaları',
  'Selahattin Demirtaş',
  'Kuruluş Osman',
  'Saddam Hüseyin',
  'Neşet Ertaş',
  'Kosova',
  'Alevilik',
  'Nazi Almanyası',
  'İslam',
  'Afganistan',
  'Ertan Saban',
  'Türk halkları',
  'Twitch',
  'Gibi',
  'Brezilya',
  'I. Murad',
  'Dersim İsyanı',
  'Dünyanın Yedi Harikası',
  'Türk Kara Kuvvetleri',
  'Hulusi Akar',
  'Hindistan',
  'Alparslan Türkeş',
  'Fatih Terim',
  'FIFA Dünya Kupası finalleri listesi',
  '500 veya daha fazla gol atan futbolcular listesi',
  'İslam mezhepleri',
  'Kenan İmirzalıoğlu',
  'Sivas Katliamı',
  'Üç Kız Kardeş (dizi)',
  'Pargalı İbrahim Paşa',
  'Billur Kalkavan',
  'Güney Kore',
  'Bizans İmparatorluğu',
  'İbrahim Kalın',
  'Malazgirt Meydan Muharebesi',
  'Celâl Bayar',
  'İspanya',
  'Suriye',
  'Josef Stalin',
  'Pablo Escobar',
  'Barış Manço',
  'Avustralya',
  'Pera Palas',
  'Alparslan: Büyük Selçuklu',
  'Abdullah Gül',
  'Kıbrıs Cumhuriyeti',
  'Birleşmiş Milletler',
  'Ahmet Davutoğlu',
  'Eşkıya Dünyaya Hükümdar Olmaz karakterleri listesi',
  'Adem Kılıçcı',
  'Hasan Atilla Uğur',
  'Bir sonraki Türkiye cumhurbaşkanlığı seçimi',
  'Survivor 2020',
  'Fevzi Çakmak',
  'Mısır',
  "Muhammed'in evlilikleri",
  'Moğol İmparatorluğu',
  'Real Madrid CF',
  'Polonya',
  '2026 FIFA Dünya Kupası',
  'Yalnız Kurt',
  '31 Mart Vakası',
  'İstiklâl Marşı',
  'Sevr Antlaşması',
  'Ülkeye göre ortalama insan boyu',
  'Âşık Veysel',
  'Koç Holding',
  'Milliyetçi Hareket Partisi',
  "İslam'da mastürbasyon",
  '2022-23 UEFA Şampiyonlar Ligi',
  'İsrail',
  'Teşkilat (dizi)',
  'Ali Kuşçu',
  'Kürdistan Bölgesel Yönetimi',
  'Suudi Arabistan',
  '23 Nisan Ulusal Egemenlik ve Çocuk Bayramı',
  'Düşük hapı',
  'Rönesans',
  'İsveç',
  'Sakıp Sabancı',
  '93 Harbi',
  '1999 Gölcük depremi',
  'Çağan Atakan Arslan',
  'Türk Deniz Kuvvetleri',
  'Kuzey Makedonya',
  'TikTok',
  'Emniyet Genel Müdürlüğü',
  'Hulusi Kentmen',
  'Türkmenistan',
  'V. Murad',
  'Türk bayrağı',
  'İklim değişikliği',
  'Rahmi Koç',
  'İskender',
  'Ermeni Kırımı',
  'Çeviri',
  'Güldür Güldür',
  'Mahkum (dizi)',
  'Alparslan Arslan',
  'Özbekistan',
  'Abdülmecid Efendi',
  'Muhammed Ali',
  'Mauro Icardi',
  'Özel Kuvvetler Komutanlığı',
  'Mevlânâ Celâleddîn-i Rûmî',
  'Türkiye hükûmetleri listesi',
  'Oktay Kaynarca',
  'Kadir Mısıroğlu',
  'Gibi bölümleri listesi',
  "Türkiye'deki bankalar listesi",
  'Muhsin Yazıcıoğlu',
  'Demet Mutlu',
  'Arka Sokaklar karakterleri listesi',
  'Agnostisizm',
  'Belçika',
  "Türkiye'nin illeri",
  'Pakistan',
  'Ses Kaydedicisi (Windows)',
  'Dolmabahçe Sarayı',
  "İslam'da oral ilişki",
  'Endonezya',
  'İzmir',
  'İbrahim (Osmanlı padişahı)',
  'Komünizm',
  'I. Mehmed',
  'Sezen Aksu',
  'Galata Kulesi',
  'Metamfetamin',
  'Kıvanç Tatlıtuğ',
  "Harry Potter'daki büyüler listesi",
  'Blackpink',
  '2018 Türkiye cumhurbaşkanlığı seçimi',
  'Gürcistan',
  'Ali',
  'Tayvan',
  'Cem Yılmaz',
  'Arjantin millî futbol takımı',
  'Lüksemburg',
  'Necip Hablemitoğlu',
  'Arnavutluk',
  'Yapı Kredi Bankası',
  'Osmanlı Hanedanı',
  'EuroLeague',
  'Eşkıya Dünyaya Hükümdar Olmaz (dizi)',
  "Mustafa Kemal Atatürk'ün dinî inancı",
  'Said Nursî',
  'Mustafa Sarıgül',
  'Bulgaristan',
  'Attila',
  'FIVB Dünya Sıralaması',
  'İbrahim',
  'Nüfuslarına göre büyük şehirler listesi',
  'Tengricilik',
  'Duy Beni',
  'I. Elizabeth',
  'Irak',
  'Erkan Baş',
  'Bosna-Hersek',
  'Fransız Devrimi',
  'Demokrat Parti (1946)',
  'Cem Ersever',
  "İslam'da peygamberler ve elçiler",
  'Nükleer silaha sahip devletler listesi',
  'Sümerler',
  'Alaettin Çakıcı',
  '2019 Türkiye yerel seçimleri',
  'VIII. Henry',
  'Sabancı Holding',
  'Cahit Arf',
  '16 Büyük Türk Devleti',
  'Survivor Ünlüler - Gönüllüler',
  'Ertuğrul Gazi',
  'Stephen Hawking',
  'Winston Churchill',
  'Finlandiya',
  'Türk Devletleri Teşkilatı',
  'Bursa',
  'Seda Sayan',
  '2022-23 UEFA Avrupa Ligi',
  'Halifeler listesi',
  "Türkiye'nin ilçeleri",
  'I. Abdülhamid',
  'Norveç',
  'Kâzım Karabekir',
  'Che Guevara',
  "Almanya'daki şehirler listesi",
  'Hicrî takvim',
  'Vajina',
  'Liberalizm',
  'Türkiye Saati',
  'Portekiz',
  'Boris Johnson',
  'Civan Canova',
  'Meta, Inc.',
  'Yalı Çapkını (dizi)',
  '2002 Türkiye genel seçimleri',
  'Mehmet Ali Çelebi',
  'Ahmet Necdet Sezer',
  'Mastürbasyon',
  'Öğretmenler Günü',
  'Kedi',
  'Ajda Pekkan',
  'UTC+03.00',
  'Avrupa ülkeleri listesi',
  'Sümeyye Erdoğan',
  'Napolyon Bonapart',
  "Sivas'ın ilçeleri",
  'Vahit Kirişçi',
  'Microsoft Windows',
  'Hristiyanlık',
  'Necati Şaşmaz',
  'III. Ahmed',
  'Dursun Özbek',
  'Singapur',
  "İzmir'in ilçeleri",
  'Sarallar',
  'Çeçenistan',
  'UEFA katsayıları',
  'Oculus VR',
  'İsmail Hacıoğlu',
  'Polat Alemdar',
  'Harry Potter',
  'Amerika Birleşik Devletleri başkanları listesi',
  'Johnny Depp',
  'Tomris',
  'Call of Duty (seri)',
  'Isaac Newton',
  'Şanghay İşbirliği Örgütü',
  'Topkapı Sarayı',
  'Mete',
  'Hull City AFC',
  'Mareşal (Türkiye)',
  "Amerika Birleşik Devletleri'nin eyaletleri",
  'Karadağ',
  'Ankara Muharebesi',
  'Macaristan',
  'Disney+',
  'Türkiye Jokey Kulübü',
  'Binali Yıldırım',
  'Sureler listesi',
  "Türk Silahlı Kuvvetleri'nin askerî rütbeleri",
  'Pelé',
  'BTS',
  'General Dynamics F-16 Fighting Falcon',
  "Assassin'sCreed (seri)",
  'Kore Savaşı',
  'Sabancı ailesi',
  'Çin Seddi',
  'Selin Ciğerci',
  'Deniz Baykal',
  'Mahidevran Sultan',
  'Metin Külünk',
  "Allah'ın isimleri",
  'Halil Falyalı',
  'Türk Silahlı Kuvvetleri genelkurmay başkanları listesi',
  'Şevval Sam',
  'Recep Yazıcıoğlu',
  'IV. Baudouin',
  '15 Temmuz Şehitler Köprüsü',
  'Irak ve Şam İslam Devleti',
  'Pîrî Reis',
  'Antalya',
  'Discord',
  'İngiltere hükümdarları listesi',
  'Suriye İç Savaşı',
  "Türkiye'de büyükşehir belediyeleri",
  'III. Charles (Birleşik Krallık kralı)',
  'Net servete göre Türklerin listesi',
  'Valérien Ismaël',
  'Süleymaniye Camii',
  'Murat Karayılan',
  'UEFA Uluslar Ligi',
  'Muzaffer Özdağ',
  'Gezi Parkı olayları',
  'Berat Albayrak',
  'Oruç Reis',
  'Marie Curie',
  "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı",
  'Anıtkabir',
  'Galileo Galilei',
  'Selimiye Camii',
  'Soğuk Savaş',
  'Mîsâk-ı Millî',
  'Ragnar Lodbrok',
  'Şener Şen',
  'Osman Wöber',
  'II. Mustafa',
  'Levent Göktaş',
  'Kürdistan',
  'UEFA Avrupa Konferans Ligi',
  'Yasak Elma (dizi, 2018)',
  'İYİ Parti',
  'Güneş tutulması',
  'Philip (Edinburgh dükü)',
  'Oğuzlar',
  'Yuri Gagarin',
  'Adana',
  'Mehmet Ağar',
  'Eren Bülbül',
  'Angelina Jolie',
  'Hacı Bayram-ı Veli',
  'Diyarbakır',
  'Anadolu Yakası',
  'Diego Maradona',
  'Erling Haaland',
  'İsmailağa Cemaati',
  'Baykar Bayraktar Kızılelma',
  'Survivor 2018',
  'Amber Heard',
  'Zeus',
  'Leonardo da Vinci',
  'Deizm',
  'Çerkesler',
  'Türkiye İş Bankası',
  'İnsan penisi',
  'Asker sayısına göre ülkeler listesi',
  'Thomas Edison',
  'Aristoteles',
  'Destan (dizi)',
  'Balkan Savaşları',
  'Güneş Sistemi',
  'Halide Edib Adıvar',
  'MasterChef Türkiye',
  'Romanya',
  'Sri Lanka',
  '2018 FIFA Dünya Kupası',
  'Hun İmparatorluğu',
  'Beşiktaş-Galatasaray derbisi',
  'Balkan Ninnisi',
  'Adile Naşit',
  'Alâeddin Bey',
  'Moğolistan',
  'Yaşar Kemal',
  'Feyyaz Yiğit',
  'Amazon (şirket)',
  'Susurluk Kazası',
  'Sırbistan',
  'Metaverse',
  'İlhan İrem',
  'Haçlı Seferleri',
  'Uğur Aslan',
  'Şeyh Said İsyanı',
  'Gülşen',
  'Avusturya',
  '28 Şubat süreci',
  'Nagihan Karadere',
  'Türk lirası',
  'Emine Erdoğan',
  'Nihal Atsız',
  'Gültekin Uysal',
  'İnsan',
  'Premier League',
  'Kavimler Göçü',
  "Trabzon'un ilçeleri",
  'Vincent van Gogh',
  'Harry (Sussex dükü)',
  'Voleybol',
  'Ermenistan',
  'III. Vlad',
  'Yüzüklerin Efendisi (film serisi)',
  '11 Eylül saldırıları',
  'Platon',
  'Uno (kart oyunu)',
  'Farah Zeynep Abdullah',
  'Sosyalizm',
  'FIFA Dünya Kupası golcüleri',
  'Efes',
  'Donbass Savaşı',
  'Cemal Gürsel',
  'Ömer Koç',
  "Türkiye'de enflasyon",
  'Vikipedi',
  "İslam'da dört büyük melek",
  'Aziz Nesin',
  'Kuş Uçuşu (dizi)',
  'UEFA Şampiyonlar Ligi finalleri listesi',
  "II. Dünya Savaşı'nda Türkiye",
  'Orgazm',
  'Brazzers',
  'Melek Mosso',
  'Bir Peri Masalı',
  'Ogeday Girişken',
  'Yahudilik',
  'Survivor 2019',
  'Büyük sayıların adları',
  'Avrupa',
  'Türk Kara Kuvvetlerinin askerî teçhizat listesi',
  'Ahmet Çalık (futbolcu)',
  'Musa',
  'Vladimir Lenin',
  'Wayback Machine',
  'Zlatan Ibrahimović',
  'Kâbe',
  'Somer Sivrioğlu',
  'Karl Marx',
  'Zehra Güneş',
  'Danimarka',
  'Anka Neferler Tim (sayfa mevcut değil)',
  'SADAT',
  'LGBT',
  'Sanayi Devrimi',
  'Monako',
  'Z kuşağı',
  'Nemrut Dağı',
  'Steve Jobs',
  'Portekiz millî futbol takımı',
  'Büyük Taarruz',
  'Yerebatan Sarnıcı',
  'Erşan Kuneri',
  '12 hayvanlı takvim',
  'Tanzimat Fermanı',
  'VII. Henry',
  'Karagöz ve Hacivat',
  'Türkiye Kupası',
  'The Walking Dead (dizi)',
  'Ahmet Mahmut Ünlü',
  'Haluk Bilginer',
  'Cadılar Bayramı',
  'Vikingler',
  'Karlofça Antlaşması',
  'Âdem',
  'Mike Tyson',
  'Emevîler',
  'Bekir Bozdağ',
  '2023 Türkiye genel seçimleri',
  'E-Okul',
  'Nasreddin Hoca',
  'Kardeşlerim',
  'Anavatan Partisi',
  'Pornografi',
  '2002 FIFA Dünya Kupası',
  'Hiram Abas',
  'Mondros Mütarekesi',
  'Mohaç Muharebesi (1526)',
  'Ethem Sancak',
  'Oğuzhan Uğur',
  "I. Dünya Savaşı'nda Osmanlı cepheleri",
  'Futbol',
  'Roma rakamları',
  'Münevver Karabulut cinayeti',
  'Tac Mahal',
  '2023 Türkiye cumhurbaşkanlığı seçimi',
  'Türk Kurtuluş Savaşı Batı Cephesi',
  'Ömer Faruk Gergerlioğlu',
  'Trabzonspor (futbol takımı)',
  'Mynet',
  'Şeyh Said',
  'Türkiye ekonomisi',
  'G',
  'Ömer Hayyam',
  "Şehzade Bayezid (I. Süleyman'ın oğlu)",
  'Kemal Sunal filmografisi',
  "Türklerin İslam'a geçişi",
  'Manchester United FC',
  'Haziran 2015 Türkiye genel seçimleri',
  'Kaderimin Oyunu (dizi)',
  'Meksika',
  'Filiz Akın',
  'Yeniçeri',
  'Hasan Can Kaya',
  'Halil İnalcık',
  'Hepsiburada',
  'Fenerbahçe-Galatasaray derbisi',
  'Windsor Hanedanı',
  'Kürt tarihi',
  'Okan Buruk',
  'Recep İvedik 7',
  'Bir Zamanlar Çukurova',
  'Büyük Selçuklu sultanları listesi',
  'Ben Bu Cihana Sığmazam',
  'Michael Jackson',
  'Kuzey Kore',
  'Kaan Urgancıoğlu',
  'Fahriye Evcen',
  'Sefo',
  'Camilla (Birleşik Krallık kraliçesi)',
  'Arda Turan',
  'Ronaldo',
  'BİM',
  'Hititler',
  'Avrupa Birliği üyesi ülkeler',
  '2022 FIVB Voleybol Kadınlar Milletler Ligi',
  'RMS Titanic',
  'Dünyanın coğrafi merkezi',
  'Göyce Zengezur Türk Cumhuriyeti (sayfa mevcut değil)',
  'Margaret (Snowdon kontesi)',
  'Birleşik Arap Emirlikleri',
  'Hadise',
  'Uluslararası telefon kodları listesi',
  'Halit Kıvanç',
  'Demet Özdemir',
  'Leonardo DiCaprio',
  'G20',
  'Arda Güler',
  'Coğrafî keşifler',
  'İstatistiksel makine çevirisi',
  'Erden Timur',
  'Beşiktaş-Fenerbahçe derbisi',
  '28 Şubat Süreci',
  'Masonluk',
  'Alexsandro de Souza',
  'Marshall Adaları',
  'Çingeneler',
  'Mezarlık (film serisi)',
  "Türkiye'de yayın yapan televizyon kanalları listesi",
  'İkinci Meşrutiyet',
  'Barış Akarsu',
  "Türkiye'de seçimler",
  'Demokrat Parti (2007)',
  'Merve Boluğur',
  'Şebnem Korur Fincancı',
  'Türkiye-PKK çatışması',
  'Dünya Kadınlar Günü',
  "İslam'da eşcinsellik",
  'Jägermeister',
  'Hârizmî',
  "Avrupa'da Yılın Futbolcusu",
  'Bergen (film)',
  'Rishi Sunak',
  'Anadolu Selçuklu sultanları listesi',
  'Ebru Özkan',
  'Trablusgarp Savaşı',
  'Müge Anlı',
  'Erkek erkeğe seks',
  'Türkan Şoray',
  'Antik Mısır',
  'Nuri Demirağ',
  "10 Kasım Atatürk'ü anma günü ve Atatürk haftası",
  'Tarkan',
  'Ayberk Pekcan',
  'Gülşen Bubikoğlu',
  'Brezilya millî futbol takımı',
  'Seni Kalbime Sakladım',
  'Orhan Veli Kanık',
  'İtilaf Devletleri',
  'Michy Batshuayi',
  'Nurbanu Sultan',
  'İrlanda',
  'Basketbol Süper Ligi şampiyonları listesi',
  'Defne Joy Foster',
  'Kusursuz Kiracı',
  'Konya',
  'Tarık Akan',
  'Memduh Ün',
  'Kerbelâ Olayı',
  'Mihail Gorbaçov',
  'Canan Kaftancıoğlu',
  'Fyodor Dostoyevski',
  'VIII. Edward',
  'Sultanahmet Camii',
  'Scottish Fold',
  'Bitcoin',
  'Hakan Şükür',
  'Tuzak (dizi)',
  'İstanbul belediye başkanları listesi',
  'Tuba Büyüküstün',
  'Birce Akalay',
  'Ekvador',
  'Maske Kimsin Sen?',
  'Brad Pitt',
  'Türkiye kadın millî voleybol takımı',
  'Atv (Türkiye)',
  'Vietnam Savaşı',
  'Ziraat Bankası',
  'Harry Potter (film serisi)',
  'Safiye Sultan',
  'Gökhan Keser',
  "Türk Silahlı Kuvvetleri'nde askerî rütbeler",
  '2024 Avrupa Futbol Şampiyonası elemeleri',
  'Breaking Bad',
  'JİTEM',
  'Seyit Onbaşı',
  'Game of Thrones',
  'Danilo Zanna',
  'Terakkiperver Cumhuriyet Fırkası',
  'Nükleer silah',
  'Zazalar',
  'Anne Boleyn',
  "Mihrimah Sultan (I. Süleyman'ın kızı)",
  'Jül Sezar',
  'Dünyayla Benim Aramda',
  'Pi sayısı',
  'Ömer Tuğrul İnançer',
  'Kulüp (dizi)',
  "2022'de Türkiye'de televizyon",
  'Sabiha Gökçen',
  'Dünyanın en zenginleri listesi',
  'Hıncal Uluç',
  'Burak Çelik',
  'V. George',
  'Roman Abramoviç',
  'Sıcak Kafa',
  'Liz Truss',
  "Barbaroslar: Akdeniz'in Kılıcı",
  'Memlûk Devleti',
  'Abbâsîler',
  'Anadolu Grubu',
  'Kırım',
  'Nef Stadyumu',
  'Freddie Mercury',
  'Fenerbahçe-Galatasaray futbol maçları listesi',
  'Kasaba Doktoru',
  'Gündüz Bey',
  'Reform (tarih)',
  'Ay',
  'Yakamoz S-245',
  'Trabzon',
  'Hayko Cepkin',
  'Dünyada dinlere göre nüfus',
  'Baykar Bayraktar Akıncı',
  'Doğru Yol Partisi',
  'Mehmet Yalçınkaya',
  '2024 Türkiye yerel seçimleri',
  '2020 Avrupa Futbol Şampiyonası',
  'Ergenekon davaları',
  'En çok izlenen Türk yapımı 100 film',
  'Marvel Sinematik Evreni',
  'Kadir Şeker davası',
  'Sema Aydemir',
  'Türk mitolojik figürlerinin listesi',
  'Çember (film serisi)',
  'William (Galler prensi)',
  'Murat Sancak',
  '2022 FIFA Dünya Kupası elemeleri (UEFA)',
  'Belarus',
  'British Shorthair',
  'Sedat Şahin',
  'İç Anadolu Bölgesi',
  'Türkiye devlet protokolü',
  'Karahanlılar',
  'NFT',
  'Hezârfen Ahmed Çelebi',
  'Osmanlı İmparatorluğu kuruluş dönemi',
  'İlluminati',
  'Paris Saint-Germain FC',
  'Jeff Bezos',
  'Üç Kuruş',
  'Halepçe Katliamı',
  'Basketbol',
  'Pablo Picasso',
  'Daron Acemoğlu',
  'Budizm',
  'Nevruz',
  'Özgür Demirtaş',
  'Senegal',
  'Google Earth',
  'Mert Yazıcıoğlu',
  'Hırvatistan',
  'Osman Hamdi Bey',
  'Juan Mata',
  'Türk mitolojisi',
  'Hakim (dizi)',
  'Michael Schumacher',
  'Avatar (film)',
  'İbrahim Yınal',
  'Akasya Durağı',
  'Yaşar Güler',
  'Ramazan Kadirov',
  'Fenerbahçe (basketbol takımı)',
  'Asal sayıların listesi',
  'Sauron',
  'Şeriat',
  '1999 Düzce depremi',
  'Kara Tahta (dizi)',
  'Cedi Osman',
  'Marmara Bölgesi',
  'Susurluk kazası',
  '2014 FIFA Dünya Kupası',
  'Kırkpınar başpehlivanları',
  'Karim Benzema',
  'Bilal Erdoğan',
  'Jale İnan',
  'Targaryen hanedanı',
  'Soma Faciası',
  'Ukrayna tarihi',
  'Mezopotamya',
  'Hacı Bektaş-ı Veli',
  'Memleket Partisi',
  'Faşizm',
  'Sera Kadıgil',
  'Ebrar Karakurt',
  'Kırım Savaşı',
  'Eski Sovyet ülkeleri',
  'Ekşi Sözlük',
  'Mahir Çayan',
  'İyilik (dizi)',
  "İstanbul'daki üniversiteler listesi",
  'Bir Küçük Gün Işığı',
  'Gaziantep',
  'Kudüs',
  'İPhone',
  'Demokrasi ve Atılım Partisi',
  'Dele Alli',
  'Ceyda Kasabalı',
  'Fârâbî',
  'Annenin Sırrıdır Çocuk',
  '2022-23 UEFA Uluslar Ligi',
  'En çok görüntülenen YouTube videoları listesi',
  'El Salvador',
  'Eşekle cinsel ilişki',
  'Lockheed Martin F-35 Lightning II',
  'Bâb-ı Âli Baskını',
  'FC Barcelona',
  '2022-23 UEFA Avrupa Konferans Ligi',
  'Roboski Katliamı',
  'Alina Boz',
  'Millet İttifakı',
  'Nene Hatun',
  '2023 Türkiye cumhurbaşkanlığı seçimi için yapılan anketler',
  'Caner Topçu',
  'Camdaki Kız (dizi)',
  'Yandex',
  'En İyi 100 Türk Filmi',
  'Fuat Oktay',
  'Android (işletim sistemi)',
  'Burak Elmas',
  'Bundesliga',
  'Tozluyaka',
  'Kapitalizm',
  'Place (Reddit)',
  'Zeytin Ağacı (dizi)',
  'Ece Erken',
  'Rusya Silahlı Kuvvetleri',
  'On İki Ada',
  'Friedrich Nietzsche',
  'Yönetim biçimlerine göre ülkeler listesi',
  'Cemre Baysel',
  'Enner Valencia',
  'Aras Bulut İynemli',
  'Şiilik',
  '2030 FIFA Dünya Kupası',
  'Elementler listesi',
  'I. Mary',
  'Özel:Kategoriler',
  'Kategori:Vikipedi bilgilendirme sayfaları',
  'Kategori:Çok ziyaret edilen sayfalar',
  'Kategori:Kısa açıklamalı proje sayfaları'
];

List list_2021 = [
  'Porno film',
  'YouTube',
  'Türkiye',
  'Nüfuslarına göre ülkeler listesi',
  'Sedat Peker',
  'Recep Tayyip Erdoğan',
  'Osman Gazi',
  'Mustafa Kemal Atatürk',
  'Süper Lig şampiyonları listesi',
  'Seks pozisyonları',
  'İstanbul Sözleşmesi',
  'Google',
  'Osmanlı İmparatorluğu',
  'Bir sonraki Türkiye genel seçimleri için yapılan anketler',
  'II. Abdülhamid',
  'I. Süleyman',
  'Instagram',
  'Osmanlı padişahları listesi',
  'Büyük Selçuklu İmparatorluğu',
  'Türkiye cumhurbaşkanları listesi',
  'II. Dünya Savaşı',
  'I. Dünya Savaşı',
  'Alp Arslan',
  'II. Mehmed',
  'II. Elizabeth',
  'İstanbul',
  'Elon Musk',
  'Amerika Birleşik Devletleri',
  'Taliban',
  'Dünya',
  'Barbaros Hayreddin Paşa',
  'Mehmet Ağar',
  'Netflix',
  'Afganistan',
  'Naim Süleymanoğlu',
  'Kıbrıs Harekâtı',
  'Periyodik tablo',
  'Montrö Boğazlar Sözleşmesi',
  'Türkiye başbakanları listesi',
  'Lozan Antlaşması',
  'Hürrem Sultan',
  'Cebelitarık',
  'I. Melikşah',
  'Anal seks',
  'İntihar yöntemleri',
  '2022 UEFA ülkeler sıralaması',
  'Cristiano Ronaldo',
  'Facebook',
  '2020 Avrupa Futbol Şampiyonası',
  'Muhammed',
  'I. Selim',
  'İsrail',
  'Mesut Özil',
  'Bitcoin',
  'Ahmed Sencer',
  'YouTube erişiminin engellenmesi',
  'Çanakkale Savaşı',
  'IV. Murad',
  'Yüzölçümlerine göre ülkeler listesi',
  'Ülkeler listesi',
  'Cumhuriyet Halk Partisi',
  'Türk Kurtuluş Savaşı',
  'II. Selim',
  'Aziz Sancar',
  'WhatsApp',
  'Büyük Selçuklu sultanları listesi',
  'Ebrar Karakurt',
  'Carles Puigdemont',
  'PKK',
  'Anadolu Selçuklu Devleti',
  'Fenerbahçe (futbol takımı)',
  'Deniz Gezmiş',
  'Adolf Hitler',
  'Osman Kavala',
  'Almanya',
  'Kurtlar Vadisi karakterleri listesi',
  'I. Ahmed',
  'Twitter',
  'Meslekler listesi',
  'Adalet ve Kalkınma Partisi',
  'Orhan Gazi',
  'Göbeklitepe',
  'İsmet İnönü',
  'Süper Lig',
  'Süleyman Soylu',
  'Türkler',
  'Eşkıya Dünyaya Hükümdar Olmaz karakterleri listesi',
  '69 (seks pozisyonu)',
  'Cengiz Han',
  'Abdullah Öcalan',
  'Malhun Hatun',
  'Kurtlar Vadisi Pusu karakterleri listesi',
  'Gmail',
  'Meral Akşener',
  'Galatasaray (futbol takımı)',
  'III. Mehmed',
  'Adnan Menderes',
  'Birleşik Krallık',
  'Türkiye futbol şampiyonları listesi',
  'III. Murad',
  'Azerbaycan',
  'Kuzey Kıbrıs Türk Cumhuriyeti',
  'Pablo Escobar',
  'Kösem Sultan',
  "Nüfusuna göre Türkiye'nin illeri",
  'Ayasofya',
  "Türkiye'deki siyasi partiler listesi",
  'Oral seks',
  'İngilizce',
  'Ahmet Kaya',
  'Bülent Ecevit',
  'Uluslararası plaka işaretleri',
  'XNXX',
  'Birleşmiş Milletler',
  'Roma İmparatorluğu',
  'Kişi başına nominal GSYİH değerlerine göre ülkeler listesi',
  'Melih Bulu',
  '2021 Avrupa Kadınlar Voleybol Şampiyonası',
  'Yunus Emre',
  'Rusya',
  '12 Eylül Darbesi',
  '28 Şubat süreci',
  'Rasim Öztekin',
  'Mansur Yavaş',
  'Hasan Sabbah',
  'Türkiye kadın millî voleybol takımı',
  'Türk Silahlı Kuvvetleri',
  'Oruç Reis',
  'Kürtler',
  'II. Osman',
  'Sovyetler Birliği',
  '2021-22 UEFA Avrupa Ligi',
  'Burak Elmas',
  'Sabahattin Ali',
  'Albert Einstein',
  'İttihat ve Terakki',
  'Mescid-i Aksa',
  'Turgut Özal',
  'Türkiye Büyük Millet Meclisi',
  'Google Çeviri',
  'VI. Mehmed',
  'Ülke bayrakları listesi',
  'Uğur Şahin',
  'Beşiktaş (futbol takımı)',
  'Ermeni Kırımı',
  'Kurtlar Vadisi (dizi)',
  'Trendyol',
  'Ahmet Burak Erdoğan',
  'Dünyanın Yedi Harikası',
  'Abdullah Çatlı',
  'Z kuşağı',
  'Eşkıya Dünyaya Hükümdar Olmaz (dizi)',
  'Susurluk kazası',
  'Süleyman Demirel',
  'Nikola Tesla',
  'Çin',
  'II. Murad',
  'Çukur (dizi)',
  'Orhun Yazıtları',
  'Ferhan Şensoy',
  'Türkiye hükûmetleri listesi',
  'Türkçe',
  'Selçuk Bayraktar',
  'Müslüm Gürses',
  'Dünya genelinde ortalama insan boyu',
  'Demokrat Parti (1946)',
  "Antalya'nın ilçeleri",
  'Celâleddin Harezmşah',
  'Mehmet Âkif Ersoy',
  'İbn-i Sina',
  "Râbi'a Bala Hâtun",
  'İbrahim Tatlıses',
  'Çernobil Faciası',
  'Zehra Güneş',
  '27 Mayıs Darbesi',
  'Sergen Yalçın',
  '2021-22 UEFA Avrupa Konferans Ligi',
  '500 veya daha fazla gol atan futbolcular listesi',
  'Kemal Kılıçdaroğlu',
  'UEFA Şampiyonlar Ligi',
  'Ali Babacan',
  'Arka Sokaklar (dizi)',
  'İran',
  'Yılmaz Güney',
  'Anadolu Selçuklu sultanları listesi',
  'İsviçre',
  'II. Mahmud',
  '15 Temmuz Darbe Girişimi',
  'İsmail Balaban',
  'Kemal Sunal',
  'EBA',
  'I. Mustafa',
  'Kurtlar Vadisi Pusu',
  'Enver Paşa',
  'II. Bayezid',
  'Necmettin Erbakan',
  'Ankara',
  'İbrahim (padişah)',
  'LGBT',
  '45. doğu meridyeni',
  "Muğla'nın ilçeleri",
  'Yahudilik',
  'Lionel Messi',
  'Fransa',
  "Türkiye'nin en zengin 100 ailesi listesi",
  'I. Bayezid',
  'İsa',
  'Brawl Stars',
  'Diana (Galler prensesi)',
  'Rauf Denktaş',
  'Nâzım Hikmet',
  'Cinsel ilişki',
  'İngiltere',
  'Omegle',
  'Yunan mitolojisi',
  'Timur',
  'Liberalizm',
  'Kıbrıs Cumhuriyeti',
  'Abdülmecid',
  'Bir sonraki Türkiye genel seçimleri',
  'Göktürk Kağanlığı',
  'Soğuk Savaş',
  'Japonya',
  "İslam'da mastürbasyon",
  'Türk Hava Kuvvetleri',
  "İstanbul'un Fethi",
  'Kanada',
  'Dersim İsyanı',
  'Neşet Ertaş',
  'Roblox',
  'Camdaki Kız (dizi)',
  'Pınar Deniz',
  'Sevr Antlaşması',
  'Mimar Sinan',
  'Kudüs',
  'III. Selim',
  'İnsan penisi',
  "Harry Potter'daki büyüler listesi",
  'Asperger sendromu',
  'Koç Holding',
  'Kenan Evren',
  'İstiklâl Marşı',
  'Hristiyanlık',
  'Türk devletleri listesi',
  'Avrupa Birliği',
  'Malazgirt Meydan Muharebesi',
  'Sezgin Baran Korkmaz',
  'Sivas Katliamı',
  'Doğan Cüceloğlu',
  '29 Ekim Cumhuriyet Bayramı',
  'Satoshi Nakamoto',
  'Çukur karakterleri listesi',
  'Amerika Birleşik Devletleri başkanları listesi',
  "İslam'da eşcinsellik",
  'Karadağ',
  'Squid Game',
  'Mahmut Özer',
  'Fransız Devrimi',
  'Güneş Sistemi',
  'Selahaddin Eyyubi',
  'Acun Ilıcalı',
  'Ali Koç',
  'Sezai Karakoç',
  'Mustafa Cengiz',
  'Pelikan (grup)',
  'Pargalı İbrahim Paşa',
  'Astral seyahat',
  'Âşık Veysel',
  'Kuruluş Osman',
  'Uyanış: Büyük Selçuklu',
  "Balıkesir'in ilçeleri",
  'Teşkilat (dizi)',
  'İslam mezhepleri',
  'Pakistan',
  'Berat Albayrak',
  'Budizm',
  'IV. Mehmed',
  'Hindistan',
  'Bizans İmparatorluğu',
  'Hakan Fidan',
  "I. Dünya Savaşı'nda Osmanlı cepheleri",
  'Burcu Biricik',
  'Harry Potter (film serisi)',
  'Jeff Bezos',
  'La casa de papel',
  'Sümerler',
  'Harezmşahlar Devleti',
  'Süveyş Kanalı',
  'Berkyaruk',
  'Sabancı ailesi',
  'Moğol İmparatorluğu',
  'NATO',
  'Ertuğrul Gazi',
  "Adem ve Havva'nın çocukları",
  'Filistin Devleti',
  'Muhammed Tapar',
  'Ekrem İmamoğlu',
  'Alaattin Çakıcı',
  'Hollanda',
  'Türk Kurtuluş Savaşı Batı Cephesi',
  'Rönesans',
  'V. Mehmed',
  'Alparslan Türkeş',
  '31 Mart Vakası',
  'Twitch',
  'I. Murad',
  '30 Ağustos Zafer Bayramı',
  'Türk bilim insanları listesi',
  'Münevver Karabulut cinayeti',
  "Türkiye'nin illeri",
  'İslam',
  'Misyoner pozisyonu',
  'UEFA Avrupa Konferans Ligi',
  'Muhsin Yazıcıoğlu',
  'Terakkiperver Cumhuriyet Fırkası',
  'Panseksüellik',
  'Josef Stalin',
  'Alevilik',
  'Fatih Terim',
  'Sakarya Meydan Muharebesi',
  '2021-22 UEFA Şampiyonlar Ligi',
  'Abdülaziz',
  'Komünizm',
  'Barış Manço',
  'Haçlı Seferleri',
  'Ragnar Lodbrok',
  'Mondros Mütarekesi',
  'Cengiz Topel',
  'Ukrayna',
  'Devlet Bahçeli',
  'Sen Çal Kapımı',
  'Türkiye millî futbol takımı',
  'Fenerbahçe-Galatasaray derbisi',
  'Selin Ciğerci',
  'Sureler listesi',
  'Tansu Çiller',
  'Ülkelere göre Müslüman nüfusu',
  'Kenan İmirzalıoğlu',
  'Kazakistan',
  '23 Nisan Ulusal Egemenlik ve Çocuk Bayramı',
  'Yunanistan',
  'Deizm',
  'Hande Erçel',
  'Hotmail',
  'İtalya',
  '2020 Dağlık Karabağ Savaşı',
  'Türk bayrağı',
  'Nureddin Nebati',
  'Necip Fazıl Kısakürek',
  'Mısır',
  'Nominal GSYİH değerlerine göre ülkeler listesi',
  'Ahmed Yesevî',
  'Güney Kore',
  "Muhammed'in evlilikleri",
  'Alparslan Arslan',
  'Selahattin Demirtaş',
  'Saddam Hüseyin',
  'VII. Kleopatra',
  'Avustralya',
  'Kaan Urgancıoğlu',
  'Mahmut Yıldırım',
  'Celâl Bayar',
  'Oğuzlar',
  '2018 Türkiye genel seçimleri',
  'Aristoteles',
  'Üç Kuruş (dizi) (sayfa mevcut değil)',
  'Avrupa Birliği üyesi ülkeler',
  'Bir Zamanlar Çukurova',
  'Türk alfabesi',
  "Türklerin İslam'a geçişi",
  'Stephen Hawking',
  'John F. Kennedy Suikastı',
  'Sahibinden.com',
  'Özel Kuvvetler Komutanlığı',
  'Uğur Aslan',
  'Pasinler Muharebesi',
  'Tanzimat Fermanı',
  "Türkiye'nin ilçeleri",
  'Fethullah Gülen',
  'Halkların Demokratik Partisi',
  'Freddie Mercury',
  'Türk Hava Yolları',
  'Özbekistan',
  'Balkan Savaşları',
  "II. Dünya Savaşı'nda Türkiye",
  '2022 FIFA Dünya Kupası elemeleri (UEFA)',
  'Ali Atay',
  'İkinci Meşrutiyet',
  'Anadolu beylikleri',
  "Osmanlı İmparatorluğu'nda eşcinsellik",
  'Atatürk İlkeleri',
  'Norveç',
  'FIFA Dünya Kupası',
  'Mihver Devletleri',
  'Mahidevran Sultan',
  'FIVB Dünya Sıralaması',
  'Arka Sokaklar karakterleri listesi',
  'Nazi Almanyası',
  'İskender',
  'Fevzi Çakmak',
  'Bill Gates',
  'Avrupa Futbol Şampiyonası',
  'Kırmızı Oda',
  'İspanya',
  'Suriye',
  'Ömer Hayyam',
  'Karl Marx',
  'Türk halkları',
  'Kürdistan Bölgesel Yönetimi',
  "Türkiye'de asgari ücret",
  'Hande Baladın',
  'Demet Mutlu',
  "İslam'da oral ilişki",
  'Şeyh Said İsyanı',
  'Mîsâk-ı Millî',
  'Özlem Türeci',
  'Platon',
  'Hinduizm',
  'Özgecan Aslan cinayeti',
  'Metamfetamin',
  'VI. George',
  'Osmanlı Hanedanı',
  'Türk Kara Kuvvetleri',
  'Sanayi Devrimi',
  "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı",
  'Murat Karayılan',
  'Charles (Galler prensi)',
  'Exxen',
  'Ayta Sözeri',
  'Kripto para',
  'Harry Potter',
  'TikTok',
  'İbrahim',
  'Nüfuslarına göre büyük şehirler listesi',
  'Müge Anlı',
  "Bursa'nın ilçeleri",
  'I. Kılıç Arslan',
  'Endonezya',
  'İtilaf Devletleri',
  'Dogecoin',
  'Sezen Aksu',
  'Yeniçeri',
  '93 Harbi',
  'Kuzey Makedonya',
  'I. Mehmed',
  'Altı Gün Savaşı',
  "İzmir'in ilçeleri",
  'Che Guevara',
  'Reform (tarih)',
  'Thomas Edison',
  'Mitoz',
  'E-Devlet (Türkiye)',
  'Finlandiya',
  'Kore Savaşı',
  'Alina Boz',
  'Türkmenistan',
  'Ali Kuşçu',
  'Yargı (dizi)',
  '2018 Türkiye cumhurbaşkanlığı seçimi',
  'Kardeşlerim',
  'Birinci Balkan Savaşı',
  'Abdullah Gül',
  'Düşük hapı',
  'II. Viyana Kuşatması',
  'Kıpçaklar',
  "Türkiye'de COVID-19 pandemisi",
  'Emniyet Genel Müdürlüğü',
  'Angela Merkel',
  'Agnostisizm',
  'Pîrî Reis',
  'Joe Biden',
  'Ahmet Davutoğlu',
  'Dünyanın en zenginleri listesi',
  'Frida Kahlo',
  'Milliyetçi Hareket Partisi',
  'Gezi Parkı olayları',
  'İsveç',
  'Winston Churchill',
  'Dünya Kadınlar Günü',
  'Ali',
  "Osmanlı İmparatorluğu'nun antlaşmaları listesi",
  'Türkiye ekonomisi',
  'Yüzüklerin Efendisi (film serisi)',
  'Olimpiyat Oyunları',
  'Pelikan grubu',
  'Vikingler',
  'Olimpiyat madalyası kazanan Türk sporcular listesi',
  'Vikipedi',
  "Konya'nın ilçeleri",
  'Hulusi Akar',
  '6-7 Eylül Olayları',
  'Erotik film',
  'Mevlânâ Celâleddîn-i Rûmî',
  'Isaac Newton',
  "İslam'ın beş şartı",
  'V. Murad',
  'Brazzers',
  'Farah Zeynep Abdullah',
  'İskandinav mitolojisi',
  'Yahudiler',
  "Barbaroslar: Akdeniz'in Kılıcı",
  'İnsan',
  'Karlofça Antlaşması',
  "İslam'da peygamberler ve elçiler",
  'Halifeler listesi',
  'Şehzade Mustafa',
  'Kırkpınar başpehlivanları',
  'Erkan Petekkaya',
  'Bulgaristan',
  'Serbest Cumhuriyet Fırkası',
  'Antik Mısır',
  'Sosyalizm',
  'Hititler',
  'Android (işletim sistemi)',
  'Erkek erkeğe seks',
  'Kartal Tibet',
  'Vincent van Gogh',
  'Aras Bulut İynemli',
  'Ahmet Necdet Sezer',
  'Said Nursî',
  'Ziya Selçuk',
  'Masumlar Apartmanı',
  'Kast sistemi',
  'Fahrettin Koca',
  'Vajina',
  'Sakıp Sabancı',
  'Irak ve Şam İslam Devleti',
  'Kürt tarihi',
  'G20',
  'İtikadî mezhep',
  'Trablusgarp Savaşı',
  'Fenerbahçe-Galatasaray futbol maçları listesi',
  'Uğur Mumcu',
  'RMS Titanic',
  'Winx Club karakterleri listesi',
  "Amerika Birleşik Devletleri'nin eyaletleri",
  'Türk Deniz Kuvvetleri',
  'Kavimler Göçü',
  'Hıdırellez',
  'Yaşar Kemal',
  'Türkiye demografisi',
  'Felsefe',
  'Tengricilik',
  'BTS',
  'EuroLeague',
  'Hazal Kaya',
  'Vladimir Putin',
  "İslam'da dört büyük melek",
  'Marie Curie',
  'III. Ahmed',
  'NATO üyesi ülkeler',
  'Attila',
  "Eurovision Şarkı Yarışması'nda Türkiye",
  'Büyük Taarruz',
  'İlluminati',
  'Galler',
  'Avrupa ülkeleri listesi',
  'Net servete göre Türklerin listesi',
  'Marvel Sinematik Evreni filmleri listesi',
  'Pornografi',
  'Michael Schumacher',
  'Büyük sayıların adları',
  'Napolyon Bonapart',
  'Cahit Sıtkı Tarancı',
  'Seks ve Genç Kız (film)',
  '2002 Türkiye genel seçimleri',
  'Vehbi Koç',
  'Oğuzhan Asiltürk',
  'Eda Erdem',
  'Binali Yıldırım',
  'Otuz Yıl Savaşı',
  'Ajda Pekkan',
  'Survivor 2021',
  'Galata Kulesi',
  'Gülseren Budayıcıoğlu',
  'Polonya',
  'Celâl Şengör',
  'Entübasyon',
  "Büyüklüğüne göre Güneş Sistemi'ndeki cisimler dizini (sayfa mevcut değil)",
  'İzmir',
  'Türk Silahlı Kuvvetleri genelkurmay başkanları listesi',
  '12 hayvanlı takvim',
  'Cem Ersever',
  'Hun İmparatorluğu',
  "Mihrimah Sultan (I. Süleyman'ın kızı)",
  'Din',
  'Mete Gazoz',
  'Burak Deniz',
  'Philip (Edinburgh dükü)',
  'Tuğrul',
  'Nurbanu Sultan',
  'Şevval Sam',
  'Breaking Bad',
  'Nikos Sampson',
  'Bosna-Hersek',
  'Mareşal (Türkiye)',
  'Kapitalizm',
  "Türkiye'deki bankalar listesi",
  'Kara Ölüm',
  "Mustafa Kemal Atatürk'ün dinî inancı",
  'Sibel Can',
  "Türkiye'de seçimler",
  'Ezgi Mola',
  'Zeus',
  'Masumiyet (dizi)',
  'Brezilya',
  '11 Eylül saldırıları',
  'Jül Sezar',
  '2021 UEFA ülkeler sıralaması',
  'Kâzım Karabekir',
  'Kadir Mısıroğlu',
  'Galileo Galilei',
  'Kuvâ-yi Milliye',
  'Cüneyt Arkın',
  'Musa',
  '2019 Türkiye yerel seçimleri',
  'Sadri Alışık',
  'Gürcistan',
  'Burcu Özberk',
  "Şehzade Bayezid (I. Süleyman'ın oğlu)",
  'Amasya Genelgesi',
  'Anavatan Partisi',
  'Arnavutluk',
  'Tac Mahal',
  '12 Mart Muhtırası',
  'Ankara Muharebesi',
  'Hasan Can Kaya',
  "Türkiye'deki üniversiteler listesi",
  'Belçika',
  'Tarık Akan',
  'Korkut Eken',
  'Türk lirası',
  'Doğu Perinçek',
  'Karayip Korsanları (film serisi)',
  "Türkiye'de büyükşehir belediyeleri",
  'Discord',
  'Vietnam Savaşı',
  'Murat Yıldırım (oyuncu)',
  'E-Okul',
  'Irak',
  'Ermenistan',
  'Mezopotamya',
  'Faşizm',
  'Recep Yazıcıoğlu',
  'Michael Jackson',
  'Büyük Buhran',
  'Şeriat',
  'Leyla ile Mecnun (dizi)',
  'Kıvanç Tatlıtuğ',
  'Hacı Bektaş-ı Veli',
  'Emine Erdoğan',
  'Leonardo da Vinci',
  'Birleşik Arap Emirlikleri',
  'Burak Yılmaz',
  'Muhammed Ali',
  'Türk dizileri listesi',
  'Mars',
  'İYİ Parti',
  'Sigmund Freud',
  'Murat Sancak',
  'Selçuklu Hanedanı',
  'Doğduğun Ev Kaderindir',
  'Kürdistan',
  'Anıtkabir',
  'Demokrasi ve Atılım Partisi',
  'Memlûk Devleti',
  'Lale Devri',
  'İbrahim Kalın',
  "İslam'da cennet",
  'Mark Zuckerberg',
  'Cunnilingus',
  'Formula 1 Dünya Sürücüler Şampiyonları listesi',
  'Shiba Inu (kripto para birimi)',
  'Oktay Kaynarca',
  'Telegram (yazılım)',
  'Dîvân-ı Hümâyun',
  'Ethereum',
  'En çok takipçisi olan Instagram hesapları listesi',
  'Nihal Atsız',
  'Meryem Boz',
  'Ford Escort',
  'Kânûn-ı Esâsî',
  'I. Abdülhamid',
  'Nizâmülmülk',
  '2021 Eurovision Şarkı Yarışması',
  "Kur'an",
  'Cem Yılmaz',
  'Rahmi Koç',
  'Kösedağ Muharebesi',
  'Cahit Arf',
  'İstanbul belediye başkanları listesi',
  "Newton'un hareket yasaları",
  'Özgür Demirtaş',
  'Suriye İç Savaşı',
  'Singapur',
  'Kosova',
  'Suudi Arabistan',
  'Mahir Çayan',
  'Nasreddin Hoca',
  "Trabzon'un ilçeleri",
  'Y kuşağı',
  'Holokost',
  'Türkiye cumhurbaşkanı',
  "Sivas'ın ilçeleri",
  'Survivor Türkiye',
  'Sivas Kongresi',
  'Türk Kara Kuvvetlerinin askerî teçhizat listesi',
  '1948 Arap-İsrail Savaşı',
  'Şener Şen',
  'Katar',
  'Çocuklar Duymasın',
  'Demokrasi',
  'Fyodor Dostoyevski',
  'Mete',
  'British Shorthair',
  'Okey 101',
  "Türkiye'de cumhuriyetin ilanı",
  'Vladimir Lenin',
  'Microsoft Windows',
  'Kanlı Noel',
  'Lewis Hamilton',
  'Feodalizm',
  'Margaret (Snowdon kontesi)',
  'Sekülerizm',
  'Alâeddin Bey',
  'Cansu Dere',
  'Alex de Souza',
  'İd, ego ve süperego',
  'Kutlu Adalı',
  'İlber Ortaylı',
  'JİTEM',
  'Oğuz Yılmaz',
  'Sümeyye Erdoğan',
  "Assassin's Creed (seri)",
  'Çin Seddi',
  'İzmir İktisat Kongresi',
  "İstanbul'un İşgali",
  'Ufuk Bayram (sayfa mevcut değil)',
  'Baht Oyunu',
  'Minecraft',
  'Macaristan',
  'Gayri safi yurt içi hasıla',
  'Gönül Dağı',
  'Nihal Yalçın',
  'Uraz Kaygılaroğlu',
  'Halide Edib Adıvar',
  'Kız Kulesi',
  'Yasak Elma (dizi, 2018)',
  'En çok abonesi olan Türk YouTube kanalları listesi',
  'Oğuz Han',
  'The Walking Dead (dizi)',
  'Danimarka',
  'Türkiye Cumhuriyeti Anayasası (1961)',
  'Cemal Gürsel',
  'Futbol',
  'Deniz Baykal',
  'Cem Karaca',
  'Necati Şaşmaz',
  'Voleybol',
  'Cem Uzan',
  'Adile Naşit',
  'Bâb-ı Âli Baskını',
  'Emre Belözoğlu',
  'Zeki Müren',
  'Şeyh Said',
  'Kıbrıs',
  'Aziz Nesin',
  'İskilipli Âtıf Hoca',
  'Osmanlı İmparatorluğu kuruluş dönemi',
  'Orhan Veli Kanık',
  'Ülke ve bölgelere göre COVID-19 pandemisi',
  'Call of Duty (seri)',
  'Kâbe',
  'Alparslan: Büyük Selçuklu',
  'Zülfü Livaneli',
  'Tuba Büyüküstün',
  'Muhteşem Yüzyıl',
  'Fahriye Evcen',
  'Arjantin',
  'Selimiye Camii',
  'Angelina Jolie',
  'Hicrî takvim',
  'Usame bin Ladin',
  'Bergen (şarkıcı)',
  'Âdem',
  'Aziz Yıldırım',
  "Adana'nın ilçeleri",
  "Diyarbakır'ın ilçeleri",
  'Topkapı Sarayı',
  'Çerkesler',
  'Bursa',
  'Adana',
  'Ezel (dizi)',
  'Mavera (dizi)',
  'Marksizm',
  'Kütüb-i Sitte',
  'Ümit Özdağ',
  'Bruce Lee',
  'Kadir Topbaş',
  'On Emir',
  'Antalya',
  'Safiye Sultan',
  'Grup (periyodik tablo)',
  'Kerbelâ Olayı',
  'El-Kaide',
  'TBMM 1. dönem milletvekilleri listesi',
  'Meksika',
  'Millî İstihbarat Teşkilatı',
  'UEFA Avrupa Ligi',
  'Muammer Kaddafi',
  'Süryaniler',
  'Moğolistan',
  'Islahat Fermanı',
  'Coğrafi keşifler',
  'Boğaziçi Üniversitesi',
  'Abbâsîler',
  'Memleket Partisi',
  'Fas',
  'Habil ve Kabil',
  'Fıkhî mezhep',
  'Hatay Devleti',
  'Emevîler',
  'III. Vlad',
  'Sabancı Holding',
  'Burak Özçivit',
  'En uzun Türkçe kelime',
  'Binance',
  'El-Cezeri',
  'Küçük Kaynarca Antlaşması',
  'Karahanlılar',
  'Pornhub',
  'Facebook, Inc.',
  'COVID-19',
  'Beşiktaş-Galatasaray derbisi',
  'Türk tarihi',
  'Türk mitolojisi',
  "Türkiye'nin gümrük kapıları listesi",
  'Melikşah',
  'Diyarbakır',
  'Sokrates',
  'John F. Kennedy',
  'Şahap Kavcıoğlu',
  'Karadeniz Bölgesi',
  'Köy enstitüsü',
  'Çingeneler',
  'On İki İmam',
  'Süleymaniye Camii',
  'Çağrı (Horasan Selçuklu meliki)',
  'Tomris',
  'Kuzgun Acar',
  'Friends',
  'Muhteşem Yüzyıl karakterleri listesi',
  'Grigori Rasputin',
  '15 Temmuz Şehitler Köprüsü',
  'Fenerbahçe teknik direktörleri listesi',
  'COVID-19 pandemisi',
  'Kuzey Kore',
  'Ahilik',
  'Savaşçı (dizi)',
  'Leonardo DiCaprio',
  'Doğu Anadolu Bölgesi',
  'Haluk Levent',
  'İstiklâl mahkemesi',
  'Postmodernizm',
  'Bâtınîlik',
  'Gigi Hadid',
  "Avrupa'da Yılın Futbolcusu",
  'Türkiye-PKK çatışması',
  'Magna Carta',
  'Biseksüellik',
  'Milletler Cemiyeti',
  'II. Mustafa',
  'I. Elizabeth',
  'Tacikistan',
  'Eşcinsellik',
  'Ada Masalı',
  "Türkiye'deki iklim çeşitleri",
  'Maraşlı (dizi)',
  'Babil',
  'Balkan Antantı',
  'Batuhan Karacakaya',
  'Rothschild ailesi',
  'En çok görüntülenen YouTube videoları listesi',
  'Körfez Savaşı',
  'Alperen Duymaz',
  'Damla Sönmez',
  'Friedrich Nietzsche',
  'Haluk Bilginer',
  'Steve Jobs',
  'Osmanlı İmparatorluğu duraklama dönemi',
  'Akıncı (dizi)',
  'İrlanda',
  'Doğru Yol Partisi',
  'Heath Ledger',
  'Mudanya Mütarekesi',
  'Canan Kaftancıoğlu',
  'Oculus VR',
  'Mayoz',
  'Funda Eryiğit',
  'Haziran 2015 Türkiye genel seçimleri',
  'Küresel ısınma',
  'Bir sonraki Türkiye cumhurbaşkanlığı seçimi',
  'Migros (Türkiye)',
  'Şiilik',
  'Veli Küçük',
  "Kayseri'nin ilçeleri",
  'Namık Kemal',
  'DNA',
  'Gaziantep',
  'Masonluk',
  'Güldür Güldür',
  'Konya',
  'Efes',
  'İç Anadolu Bölgesi',
  "İstanbul'daki üniversiteler listesi",
  'Naruto: Shippuuden bölümleri listesi',
  'Güneydoğu Anadolu Bölgesi',
  'Saltanatın kaldırılması',
  'Hiram Abas',
  'Cemal Süreya',
  'Aydınlanma Çağı',
  'Reşat Nuri Güntekin',
  'Alman İmparatorluğu',
  'Orhan Pamuk',
  'Süleyman Şah',
  'Yönetim biçimlerine göre ülkeler listesi',
  'III. Makarios',
  'Avusturya',
  'Peaky Blinders (dizi)',
  'Gümrü Antlaşması',
  'UEFA katsayıları',
  'Ömer Faruk Gergerlioğlu',
  'Letonya',
  'BİM',
  'Baykar Bayraktar TB2',
  "Türkiye'deki yanardağlar",
  'İskoçya',
  "Türkiye'de askerî müdahaleler",
  'Tayvan',
  '16 Büyük Türk Devleti',
  'İlayda Alişan',
  'Polat Alemdar',
  'Junko Furuta cinayeti',
  'Romanya',
  'Nemrut Dağı',
  'Zazalar',
  'Melis Sezen',
  'Fırat Çakıroğlu cinayeti',
  'Süper Lig gol kralları listesi',
  'Mesut Yılmaz',
  'Fetret Devri',
  'Ayça Ayşin Turan',
  'Abdülmecid Efendi',
  'Seyit Onbaşı',
  'Gülşen Bubikoğlu',
  'VIII. Edward',
  'Erkan Baş',
  'Benito Mussolini',
  'Karagöz ve Hacivat',
  'Kemal Sunal filmografisi',
  'Fârâbî',
  'Kırgızistan',
  'I. Mahmud (Büyük Selçuklu sultanı)',
  'Öykü Çelik',
  "Şehzade Mehmed (I. Süleyman'ın oğlu)",
  'Cumhurbaşkanlığı Sarayı (Türkiye)',
  'Grand Theft Auto V',
  'Güney Afrika Cumhuriyeti',
  'Türk Kurtuluş Savaşı Güney Cephesi',
  'Alevi nüfusu',
  'Nuri Bilge Ceylan',
  'Sosyoloji',
  'Zlatan Ibrahimović',
  'Lüksemburg',
  'Orta Çağ',
  'Roboski Katliamı',
  'Virüs',
  'Sihirli Annem',
  'Lezbiyen',
  'General Dynamics F-16 Fighting Falcon',
  'Kan grubu',
  'Esat Oktay Yıldıran',
  'Oksijen doygunluğu (tıp)',
  'Donald Trump',
  'XXXTentacion',
  'Kanal İstanbul',
  'Osmanlı padişah eşleri listesi',
  'Yeni Zelanda',
  'Bülent Ersoy',
  'Filiz Akın',
  'Gülse Birsel',
  'İstanbul Üniversitesi',
  'Camp David Sözleşmesi',
  'Balkanlar',
  'Sözlük',
  'Küba',
  "Ankara'nın ilçeleri",
  'Mohaç Muharebesi (1526)',
  'Özel:Kategoriler',
  'Kategori:Vikipedi bilgilendirme sayfaları',
  'Kategori:Çok ziyaret edilen sayfalar',
  'Kategori:Kısa açıklamalı proje sayfaları'
];

void main() async {
  API api = API();
  for (int i = 0; i < list_2021.length; i++) {
    print("index $i");
    while (true) {
      try {
        List defs = await api.call_api(list_2021[i], "1", "q_a", "tr");
        print("Questions Anser 1 $defs");
        List defs1 = await api.call_api(list_2021[i], "2", "q_a", "tr");
        print("Questions Anser 2 $defs1");

        List defs2 = await api.call_api(list_2021[i], "0", "s_m", "tr");
        print("TS  $defs2");

        break;
      } catch (r) {}
    }
  }

  //List defs1 = await api.call_api("NATO", "0", "q_a", "en");

  //print("DEFS:${defs1[0]}");
}
