# Generated by Django 4.1.2 on 2022-10-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_q_a_type_q_a"),
    ]

    operations = [
        migrations.CreateModel(
            name="S_M",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default={})),
            ],
        ),
    ]
