# Generated by Django 4.1.2 on 2022-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_s_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="q_a", name="data", field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="question_answer_database",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="s_m", name="data", field=models.JSONField(default=dict),
        ),
    ]
